### ISSUE TITLE
Refactor: 코드 리뷰 피드백 반영

### ISSUE THREAD

**Issue by ssuminii** [Dev-FE-1/Toy_Project_II_TEAM5#83]
## 어떤 기능인가요?

> 코드 리뷰 피드백 바탕으로 코드 리팩토링

## 작업 상세 내용

- [x] 수민
- [x] 원지
- [x] 호연
- [x] 동혁
- [x] 윤환

**Comment by kimpra2989** [comment]
모두들 참 잘했어요~❤️❤️❤️
